[auth]
redirect_uri = "https://quizes.streamlit.app/oauth2callback"
cookie_secret = "5wvB7f!d$9kL&Z2@vMpN#XtQs3rU^8ypGjPk4Zh%Yr$Qo7"
client_id = "86275593624-mgc091gebp1don7tf4fu1t5op5t7lnep.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
